#!/usr/bin/bash
# blkid -s UUID -o value
# dmesg | grep 'lpj='

efibootmgr -B -b 0000
efibootmgr -c \
-d /dev/sda \
-p 1 \
-l /vmlinuz-linux \
-L "Arch" \
-u 'cryptdevice=UUID=xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx:luksdev initrd=\initramfs-linux.img initrd=\intel-ucode.img quiet splash logo.nologo fbcon=nodefer pcie_aspm=off loglevel=3 udev.log_level=3 udev.log_priority=3 i915.modeset=1 i915.fastboot=1 zswap.enabled=0 nowatchdog root=UUID=xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx rootfstype=ext4 rw libahci.ignore_sss=1 raid=noautodetect lpj=xxxxxxx' \
-v

exit 0
