#!/usr/bin/bash
# blkid -s UUID
# dmesg | grep 'lpj='
# Disable Spectre and Meltdown mitigations, configuring the kernel command line: .. --unicode '.. mitigations=off spectre_v2=off ..'

efibootmgr --delete-bootnum --bootnum 0000 &>/dev/null
efibootmgr --create \
--disk /dev/sda \
--part 1 \
--label "arch" \
--loader /vmlinuz-linux-zen \
--unicode 'cryptdevice=UUID=xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx:luksdev initrd=\intel-ucode.img initrd=\initramfs-linux-zen.img quiet bgrt_disable logo.nologo fbcon=nodefer pcie_aspm=off loglevel=0 debugfs=off rd.emergency=reboot rd.shell=0 panic-on-corruption oops=panic module.sig_enforce=1 lockdown=confidentiality ipv6.disable=1 i915.modeset=1 i915.fastboot=1 zswap.enabled=0 nowatchdog root=UUID=xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx rootfstype=ext4rw libahci.ignore_sss=1 raid=noautodetect lpj=xxxxxxx' \
--verbose

exit 0
